services:
    postgres:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_USER: sa
            POSTGRES_PASSWORD: password
            PG_DATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - '5432:5432'
        networks:
            - db-network
        restart: unless-stopped
    mongo:
        container_name: mongo
        hostname: mongo
        image: mongo:jammy
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        volumes:
            - mongo:/data/db
        ports:
            - '27017:27017'
        networks:
            - db-network
        restart: unless-stopped
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - '5050:80'
        networks:
            - db-network
        restart: unless-stopped

networks:
    db-network:
        driver: bridge
volumes:
    mongo:
    postgres:
    pgadmin: