spring:
    application:
        name: message-system
    cassandra:
        keyspace-name: "\"message_system\""
        contact-points: localhost:9042, localhost:9043
        username: ${CASSANDRA_LOGIN_DEV}
        password: ${CASSANDRA_PASSWORD_DEV}
        local-datacenter: Mars

eureka:
    client:
        enabled: false

cassandra:
    migration:
        keyspace-name: "\"message_system\""


