spring:
    application:
        name: message-system
    cassandra:
        keyspace-name: ${DEV_CASSANDRA_KEYSPACE:"message_system"}
        contact-points: ${DEV_CASSANDRA_CONTACT_POINTS:localhost:9042}
        username: ${CASSANDRA_LOGIN_DEV:cassandra}
        password: ${CASSANDRA_PASSWORD_DEV:cassandra}
        local-datacenter: ${DEV_CASSANDRA_LOCAL_DATACENTER:Mars}


eureka:
    client:
        enabled: true
        service-url:
            defaultZone: ${DEV_EUREKA_URL:http://localhost:8761/eureka}

cassandra:
    migration:
        keyspace-name: ${DEV_CASSANDRA_KEYSPACE:"message_system"}

server:
    port: 8100
client:
    user-service-base-url: http://user-service
    base-message-agent: security-service
