spring:
    application:
        name: user-service
    r2dbc:
        url: ${DEV_DB_URL:r2dbc:postgresql://localhost:5432/user-service}
        username: ${DEB_DB_USER:sa}
        password: ${DEV_DB_PASSWORD:password}
    flyway:
        url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/user-service}
        user: ${DEB_DB_USER:sa}
        password: ${DEV_DB_PASSWORD:password}
        validate-migration-naming: false

eureka:
    client:
        enabled: true
        service-url:
            defaultZone: ${DEV_EUREKA_URL:http://localhost:8761/eureka}

server:
    port: 8090
