spring:
    application:
        name: user-service
    r2dbc:
        url: ${DEV_DB_URL:r2dbc:postgresql://localhost:5432/dev}
        username: ${DEB_DB_USER:root}
        password: ${DEV_DB_PASSWORD:root}
    flyway:
        url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/dev}
        user: ${DEB_DB_USER:root}
        password: ${DEV_DB_PASSWORD:root}
        validate-migration-naming: false

eureka:
    client:
        enabled: false
        service-url:
            defaultZone: ${DEV_EUREKA_URL:http://localhost:8761/eureka}

server:
    port: 8090
