spring:
    application:
        name: security-service
    datasource:
        url: ${DEV_DB_URL:r2dbc:postgresql://localhost:5432/dev}
        username: ${DEB_DB_USER:sa}
        password: ${DEV_DB_PASSWORD:password}

