spring:
    application:
        name: security-service
    r2dbc:
        url: ${DEV_DB_URL:r2dbc:postgresql://localhost:5432/dev}
        username: ${DEB_DB_USER:sa}
        password: ${DEV_DB_PASSWORD:password}
    flyway:
        url: ${DEV_DB_URL:jdbc:postgresql://localhost:5432/dev}
        user: ${DEB_DB_USER:sa}
        password: ${DEV_DB_PASSWORD:password}
        validate-migration-naming: false

eureka:
    client:
        enabled: true
        service-url:
            defaultZone: ${DEV_EUREKA_URL:http://localhost:8761/eureka}



security:
    jwt-prefix: 'Bearer '
    basic-prefix: 'Basic '
    role-key: 'role'
    secret-key: '722236765770276c3c21344b6a455f3662447d3b4b7b3e2c2b707d7e3e'
    token-live-time: 1800000

server:
    port: 8080
